# Generated by Django 3.2.7 on 2021-09-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        # Here we can write costom sql that is exectued whenever the migration is run.
        # The first argument is the upgrade code, and the second aargument is the code run
        # when reverting migration changes
        migrations.RunSQL('''
            INSERT INTO store_collection (title)
            VALUES ('My First Collection')
         ''', '''
            DELETE FROM store_collection
            WHERE  title = 'My First Collection' 
         ''')
    ]
