# Generated by Django 3.2.7 on 2021-09-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membership_type',
            new_name='membership',
        ),
    ]
